FROM python:3.9-buster
ENV PYTHONUNBUFFERED=1

WORKDIR /src
COPY wait-for-it.sh /wait-for-it.sh

RUN pip3 install --upgrade pip
RUN pip3 install "uvicorn[standard]"
RUN pip3 install --no-cache-dir --upgrade -r /src/requirements.txt

RUN chmod +x /wait-for-it.sh

ENTRYPOINT ["bash","entrypoint.sh"]
