FROM python:3.9-buster
ENV PYTHONUNBUFFERED=1

WORKDIR /src
COPY ./src /src

RUN pip3 install --upgrade pip
RUN pip3 install "uvicorn[standard]"
RUN pip3 install --no-cache-dir --upgrade -r /src/requirements.txt

RUN chmod +x /src/wait-for-it.sh

ENTRYPOINT ["bash","/src/entrypoint.sh"]
